import {useEffect,useState} from 'react';
import {MapContainer,TileLayer,CircleMarker,Popup,useMap,useMapEvents} from 'react-leaflet';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {Layers,LocateFixed} from 'lucide-react';
import {viewport} from '../../services/issues';
import {Badge} from '../../components/ui';
import 'leaflet/dist/leaflet.css';
function Features({demo,severity}:{demo:boolean;severity:string}){const map=useMap();const [bounds,setBounds]=useState<number[]>(()=>{const b=map.getBounds();return [b.getWest(),b.getSouth(),b.getEast(),b.getNorth()];});useMapEvents({moveend(){const b=map.getBounds();setBounds([b.getWest(),b.getSouth(),b.getEast(),b.getNorth()]);}});const {data,error}=useQuery({queryKey:['viewport',demo,bounds,severity],queryFn:({signal})=>viewport(demo,bounds,severity,signal),staleTime:15000});return <>{error&&<div className="map-error" role="alert">Unable to load city signals</div>}{data?.map(i=><CircleMarker key={i.id} center={[i.latitude,i.longitude]} radius={i.severity==='CRITICAL'?8:6} pathOptions={{color:'white',weight:2,fillColor:i.severity==='CRITICAL'?'var(--critical)':i.severity==='HIGH'?'var(--warning)':'var(--primary)',fillOpacity:.95}}><Popup><strong>{i.title}</strong><p>{i.issue_id} · {i.ward}</p><Badge value={i.severity}/><p><Link to={`${demo?'/demo':''}/issues/${i.id}`}>Open issue →</Link></p></Popup></CircleMarker>)}</>;}
function Resize(){const map=useMap();useEffect(()=>{const ro=new ResizeObserver(()=>map.invalidateSize());ro.observe(map.getContainer());return()=>ro.disconnect();},[map]);return null;}
function Recenter(){const map=useMap();const {t}=useTranslation();return <button className="map-recenter" aria-label={t('city')} onClick={()=>map.setView([23.030,72.573],13)}><LocateFixed size={19}/></button>;}
export default function CityMap({demo=true,severity='',compact=false}:{demo?:boolean;severity?:string;compact?:boolean}){const {t}=useTranslation();const [basemap,setBasemap]=useState(false);return <div className={`city-map ${compact?'compact':''}`}><MapContainer center={[23.030,72.573]} zoom={13} scrollWheelZoom={!compact} zoomControl={!compact}><TileLayer key={String(basemap)} attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; CARTO' url={basemap?'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png':'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png'}/><Features demo={demo} severity={severity}/><Resize/><Recenter/></MapContainer><div className="map-legend"><span><i className="dot red"/>{t('critical')}</span><span><i className="dot amber"/>High</span><span><i className="dot blue"/>Other issues</span></div><button className="map-layer" aria-label="Switch basemap" onClick={()=>setBasemap(v=>!v)}><Layers size={17}/></button><span className="map-coordinate">23.0300° N &nbsp; 72.5730° E</span></div>;}
