import {useState} from 'react';
import type {FormEvent} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {ShieldCheck,ArrowRight} from 'lucide-react';
import {z} from 'zod';
import {requireClient,supabase} from '../services/client';
import {Logo,Language} from '../components/ui';
export default function Login(){const {t}=useTranslation();const {pathname}=useLocation();const navigate=useNavigate();const forgot=pathname==='/forgot-password',reset=pathname==='/reset-password';const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setMessage('');setBusy(true);try{const form=new FormData(e.currentTarget),client=requireClient();const email=String(form.get('email')??''),password=String(form.get('password')??'');if(!reset)z.email().parse(email);if(!forgot)z.string().min(8).max(128).parse(password);if(forgot){const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/reset-password'});if(error)throw error;setMessage('If this account exists, a password reset link has been sent.');}else if(reset){const {error}=await client.auth.updateUser({password});if(error)throw error;setMessage('Password updated. You can return to your workspace.');}else{const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;navigate('/dashboard');}}catch(err){setError(err instanceof Error?err.message:'Unable to sign in.');}finally{setBusy(false);}}return <div className="login-page"><header><Logo/><Language/></header><div className="login-layout"><aside><div className="eyebrow">CONNECTED CITY OPERATIONS</div><h1>Better visibility.<br/>Clearer decisions.<br/><span>Stronger cities.</span></h1><p>{t('heroText')}</p><div className="login-principle"><ShieldCheck/><div><strong>{t('accountable')}</strong><p>{t('accountableText')}</p></div></div></aside><section className="login-form"><h2>{t(forgot?'forgot':reset?'resetPassword':'loginTitle')}</h2><p>{t('loginText')}</p>{!supabase&&<div className="notice"><strong>{t('notConnected')}</strong><p>{t('notConnectedText')}</p></div>}<form onSubmit={e=>void submit(e)}>{!reset&&<label>{t('email')}<input name="email" type="email" required autoComplete="email" placeholder="you@city.gov.in"/></label>}{!forgot&&<label>{t('password')}<input name="password" type="password" minLength={8} maxLength={128} required autoComplete={reset?'new-password':'current-password'}/></label>}{!forgot&&!reset&&<Link to="/forgot-password">{t('forgot')}</Link>}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<button className="primary" disabled={busy||!supabase}>{busy?t('loading'):t(forgot?'sendReset':reset?'resetPassword':'signIn')}<ArrowRight size={17}/></button></form><div className="login-divider">CIVICSPHERE PREVIEW</div><Link className="button" to="/demo/dashboard">{t('demoEntry')}<ArrowUpRightIcon/></Link><small><ShieldCheck size={14}/>{t('secure')}</small></section></div></div>;}
function ArrowUpRightIcon(){return <ArrowRight size={16}/>;}
