import {useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {Search,ArrowUpRight,ChevronLeft,ChevronRight} from 'lucide-react';
import {listIssues} from '../../services/issues';
import type {Issue} from '../../types/domain';
import {Badge,Loading,ErrorState} from '../../components/ui';
export function IssueTable({issues,demo}:{issues:Issue[];demo:boolean}){const {t}=useTranslation();return <div className="table-scroll"><table><thead><tr><th>{t('issue')}</th><th>{t('severity')}</th><th>{t('status')}</th><th>{t('ward')}</th><th>{t('confidence')}</th><th/></tr></thead><tbody>{issues.map(i=><tr key={i.id}><td><Link to={`${demo?'/demo':''}/issues/${i.id}`}><small>{i.issue_id}</small><strong>{i.title}</strong></Link></td><td><Badge value={i.severity}/></td><td><Badge value={i.status}/></td><td>{i.ward}</td><td><div className="confidence"><span>{i.confidence_score}%</span><div><i style={{width:`${i.confidence_score}%`}}/></div></div></td><td><Link aria-label={i.title} to={`${demo?'/demo':''}/issues/${i.id}`}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></table>{!issues.length&&<div className="state">{t('empty')}</div>}</div>;}
export default function IssueList(){const {t}=useTranslation();const {pathname}=useLocation();const demo=pathname.startsWith('/demo');const review=pathname.endsWith('/reviews');const [filters,setFilters]=useState({search:'',severity:'',status:review?'PENDING_REVIEW':'',page:0});const result=useQuery({queryKey:['issues',demo,filters],queryFn:({signal})=>listIssues(demo,filters,signal)});function update(k:string,v:string){setFilters(f=>({...f,[k]:v,page:0}));}return <><div className="page-heading"><div><div className="eyebrow">{t('operations')}</div><h1>{t(review?'reviews':'issues')}</h1><p>{t(review?'attentionSub':'overviewSub')}</p></div><Link className="button" to={`${demo?'/demo':''}/map`}>{t('viewMap')}<ArrowUpRight size={16}/></Link></div><section className="panel"><div className="filters"><div className="search-field"><Search size={17}/><input aria-label={t('search')} placeholder={t('search')} value={filters.search} onChange={e=>update('search',e.target.value)}/></div><select aria-label={t('severity')} value={filters.severity} onChange={e=>update('severity',e.target.value)}><option value="">{t('allSeverities')}</option>{['CRITICAL','HIGH','MEDIUM','LOW','INFO'].map(s=><option key={s}>{s}</option>)}</select>{!review&&<select aria-label={t('status')} value={filters.status} onChange={e=>update('status',e.target.value)}><option value="">{t('allStatuses')}</option>{['DETECTED','PENDING_REVIEW','VERIFIED','ASSIGNED','IN_PROGRESS','RESOLVED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select>}</div>{result.isLoading?<Loading/>:result.error?<ErrorState message={result.error.message} retry={()=>void result.refetch()}/>:<IssueTable issues={result.data?.rows??[]} demo={demo}/>}<div className="table-bottom"><span>{result.data?.count??0} {t('issues')} · {t('readOnly') && (demo?t('readOnly'):'')}</span><div><button className="icon-button" aria-label="Previous page" disabled={filters.page===0} onClick={()=>setFilters(f=>({...f,page:f.page-1}))}><ChevronLeft size={16}/></button><span>{filters.page+1}</span><button className="icon-button" aria-label="Next page" disabled={(filters.page+1)*25>=(result.data?.count??0)} onClick={()=>setFilters(f=>({...f,page:f.page+1}))}><ChevronRight size={16}/></button></div></div></section></>;}
